FROM amazoncorretto:17
WORKDIR /app

# Expose the port the app runs on (modify as necessary)
EXPOSE 8080

COPY build/libs/Sample_User_API-0.0.1-SNAPSHOT.jar  /app/app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]

